/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef PLAYBUTTONONBASE_HPP
#define PLAYBUTTONONBASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <touchgfx/containers/Container.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/canvas/Circle.hpp>
#include <touchgfx/widgets/canvas/PainterRGB565.hpp>
#include <touchgfx/widgets/TextArea.hpp>

class playButtonOnBase : public touchgfx::Container
{
public:
    playButtonOnBase();
    virtual ~playButtonOnBase();
    virtual void initialize();

protected:
    FrontendApplication& application() {
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }

    /*
     * Member Declarations
     */
    touchgfx::Box box1;
    touchgfx::Circle circle1;
    touchgfx::PainterRGB565 circle1Painter;
    touchgfx::Circle circle1_1;
    touchgfx::PainterRGB565 circle1_1Painter;
    touchgfx::Box box1_1_1;
    touchgfx::Circle circle1_2;
    touchgfx::PainterRGB565 circle1_2Painter;
    touchgfx::Circle circle1_1_1;
    touchgfx::PainterRGB565 circle1_1_1Painter;
    touchgfx::TextArea textArea1;

private:

};

#endif // PLAYBUTTONONBASE_HPP
