/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef EXITSCREENVIEWBASE_HPP
#define EXITSCREENVIEWBASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <mvp/View.hpp>
#include <gui/exitscreen_screen/exitScreenPresenter.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/TextArea.hpp>

class exitScreenViewBase : public touchgfx::View<exitScreenPresenter>
{
public:
    exitScreenViewBase();
    virtual ~exitScreenViewBase();
    virtual void setupScreen();

protected:
    FrontendApplication& application() {
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }

    /*
     * Member Declarations
     */
    touchgfx::Box __background;
    touchgfx::Box box1;
    touchgfx::TextArea test3;
    touchgfx::TextArea test2;
    touchgfx::TextArea test1;

private:

};

#endif // EXITSCREENVIEWBASE_HPP
