/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/CustomContainer1_1Base.hpp>
#include <touchgfx/Color.hpp>
#include <texts/TextKeysAndLanguages.hpp>

CustomContainer1_1Base::CustomContainer1_1Base()
{
    setWidth(145);
    setHeight(26);
    boxWithBorder1.setPosition(0, 0, 145, 26);
    boxWithBorder1.setColor(touchgfx::Color::getColorFromRGB(173, 173, 173));
    boxWithBorder1.setBorderColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    boxWithBorder1.setBorderSize(1);
    add(boxWithBorder1);

    textArea1.setXY(-6, 3);
    textArea1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea1.setLinespacing(0);
    Unicode::snprintf(textArea1Buffer, TEXTAREA1_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_HZGV).getText());
    textArea1.setWildcard(textArea1Buffer);
    textArea1.resizeToCurrentText();
    textArea1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_EUIR));
    add(textArea1);
}

CustomContainer1_1Base::~CustomContainer1_1Base()
{

}

void CustomContainer1_1Base::initialize()
{

}
