/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/containers/playButtonOffBase.hpp>
#include <touchgfx/Color.hpp>
#include <texts/TextKeysAndLanguages.hpp>

playButtonOffBase::playButtonOffBase()
{
    setWidth(480);
    setHeight(272);
    box1.setPosition(155, 104, 171, 57);
    box1.setColor(touchgfx::Color::getColorFromRGB(196, 196, 196));
    add(box1);

    circle1.setPosition(115, 94, 80, 94);
    circle1.setCenter(40, 40);
    circle1.setRadius(29);
    circle1.setLineWidth(0);
    circle1.setArc(0, 360);
    circle1Painter.setColor(touchgfx::Color::getColorFromRGB(196, 196, 196));
    circle1.setPainter(circle1Painter);
    add(circle1);

    circle1_1.setPosition(286, 93, 80, 84);
    circle1_1.setCenter(40, 40);
    circle1_1.setRadius(29);
    circle1_1.setLineWidth(0);
    circle1_1.setArc(0, 360);
    circle1_1Painter.setColor(touchgfx::Color::getColorFromRGB(196, 196, 196));
    circle1_1.setPainter(circle1_1Painter);
    add(circle1_1);

    box1_1_1.setPosition(150, 112, 180, 51);
    box1_1_1.setColor(touchgfx::Color::getColorFromRGB(168, 167, 167));
    add(box1_1_1);

    circle1_2.setPosition(111, 100, 80, 94);
    circle1_2.setCenter(40.0f, 37.5f);
    circle1_2.setRadius(25.3f);
    circle1_2.setLineWidth(0);
    circle1_2.setArc(0, 360);
    circle1_2Painter.setColor(touchgfx::Color::getColorFromRGB(168, 167, 167));
    circle1_2.setPainter(circle1_2Painter);
    add(circle1_2);

    circle1_1_1.setPosition(290, 99, 80, 84);
    circle1_1_1.setCenter(40.0f, 39.5f);
    circle1_1_1.setRadius(25.3f);
    circle1_1_1.setLineWidth(0);
    circle1_1_1.setArc(0, 360);
    circle1_1_1Painter.setColor(touchgfx::Color::getColorFromRGB(168, 167, 167));
    circle1_1_1.setPainter(circle1_1_1Painter);
    add(circle1_1_1);

    textArea1.setXY(198, 119);
    textArea1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textArea1.setLinespacing(0);
    textArea1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_4U55));
    add(textArea1);
}

playButtonOffBase::~playButtonOffBase()
{

}

void playButtonOffBase::initialize()
{

}
