/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef MENUSCREENVIEWBASE_HPP
#define MENUSCREENVIEWBASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <mvp/View.hpp>
#include <gui/menuscreen_screen/menuScreenPresenter.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/TextArea.hpp>
#include <touchgfx/widgets/Button.hpp>
#include <touchgfx/widgets/Image.hpp>
#include <touchgfx/containers/SwipeContainer.hpp>
#include <touchgfx/containers/Container.hpp>
#include <touchgfx/EasingEquations.hpp>
#include <touchgfx/mixins/FadeAnimator.hpp>
#include <touchgfx/widgets/ButtonWithLabel.hpp>
#include <touchgfx/containers/scrollers/ScrollWheelWithSelectionStyle.hpp>
#include <gui/containers/CustomContainer1_1.hpp>
#include <gui/containers/CustomContainer1.hpp>
#include <touchgfx/widgets/ScalableImage.hpp>

class menuScreenViewBase : public touchgfx::View<menuScreenPresenter>
{
public:
    menuScreenViewBase();
    virtual ~menuScreenViewBase();
    virtual void setupScreen();

    virtual void scrollWheel1UpdateItem(CustomContainer1_1& item, int16_t itemIndex)
    {
        // Override and implement this function in menuScreen
    }

    virtual void scrollWheel1UpdateCenterItem(CustomContainer1& item, int16_t itemIndex)
    {
        // Override and implement this function in menuScreen
    }

    /*
     * Virtual Action Handlers
     */
    virtual void buttonMenuPlayisTriggered()
    {
        // Override and implement this function in menuScreen
    }
    virtual void buttonModePlayisTriggered()
    {
        // Override and implement this function in menuScreen
    }

protected:
    FrontendApplication& application() {
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }

    /*
     * Member Declarations
     */
    touchgfx::Box __background;
    touchgfx::TextArea textRodeo;
    touchgfx::TextArea textTest;
    touchgfx::TextArea textFree;
    touchgfx::Button nullbutton;
    touchgfx::Box exitMenuBckgrnd;
    touchgfx::Image image1;
    touchgfx::SwipeContainer swipeContainer1;
    touchgfx::Container Simhub;
    touchgfx::FadeAnimator< touchgfx::Image > imageSH1;
    touchgfx::FadeAnimator< touchgfx::Image > imageSH2;
    touchgfx::FadeAnimator< touchgfx::Image > imageSH3;
    touchgfx::FadeAnimator< touchgfx::Image > imageSH4;
    touchgfx::FadeAnimator< touchgfx::Image > imageSH5;
    touchgfx::FadeAnimator< touchgfx::Image > imageSH6;
    touchgfx::FadeAnimator< touchgfx::Image > imageSH7;
    touchgfx::FadeAnimator< touchgfx::Image > imageSH8;
    touchgfx::Image logoMenu;
    touchgfx::ButtonWithLabel playMenuButton;
    touchgfx::Container Gamemode;
    touchgfx::Box fromFree;
    touchgfx::Image image2;
    touchgfx::Image imageRodeo;
    touchgfx::ButtonWithLabel playButtonMode;
    touchgfx::ScrollWheelWithSelectionStyle scrollWheel1;
    touchgfx::DrawableListItems<CustomContainer1_1, 6> scrollWheel1ListItems;
    touchgfx::DrawableListItems<CustomContainer1, 2> scrollWheel1SelectedListItems;
    touchgfx::Image logoMode;
    touchgfx::Container Creator;
    touchgfx::ScalableImage imageFireBckgrnd;
    touchgfx::Image bilal;
    touchgfx::Image julien;
    touchgfx::TextArea textArea2;
    touchgfx::TextArea textArea2_1;
    touchgfx::TextArea textArea2_1_1;
    touchgfx::TextArea textArea2_1_1_1;
    touchgfx::ScalableImage scalableImage3;

private:

    /*
     * Callback Declarations
     */
    touchgfx::Callback<menuScreenViewBase, touchgfx::DrawableListItemsInterface*, int16_t, int16_t> updateItemCallback;
    touchgfx::Callback<menuScreenViewBase, const touchgfx::AbstractButton&> buttonCallback;

    /*
     * Callback Handler Declarations
     */
    void updateItemCallbackHandler(touchgfx::DrawableListItemsInterface* items, int16_t containerIndex, int16_t itemIndex);
    void buttonCallbackHandler(const touchgfx::AbstractButton& src);

};

#endif // MENUSCREENVIEWBASE_HPP
