/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef LOADINGSCREENVIEWBASE_HPP
#define LOADINGSCREENVIEWBASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <mvp/View.hpp>
#include <gui/loadingscreen_screen/loadingScreenPresenter.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/Button.hpp>
#include <touchgfx/widgets/TextureMapper.hpp>
#include <touchgfx/widgets/TextArea.hpp>
#include <touchgfx/widgets/TextAreaWithWildcard.hpp>

class loadingScreenViewBase : public touchgfx::View<loadingScreenPresenter>
{
public:
    loadingScreenViewBase();
    virtual ~loadingScreenViewBase();
    virtual void setupScreen();

    /*
     * Virtual Action Handlers
     */
    virtual void buttonlaunchInitSystem()
    {
        // Override and implement this function in loadingScreen
    }

protected:
    FrontendApplication& application() {
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }

    /*
     * Member Declarations
     */
    touchgfx::Box __background;
    touchgfx::Button nullbutton;
    touchgfx::Box formBackground;
    touchgfx::TextureMapper imagemapCorncat;
    touchgfx::TextArea textL3;
    touchgfx::TextArea textL2;
    touchgfx::TextArea textL1;
    touchgfx::TextAreaWithOneWildcard textDisplayTTY;
    touchgfx::Button InitButton;
    touchgfx::TextArea textInitSystem;

    /*
     * Wildcard Buffers
     */
    static const uint16_t TEXTDISPLAYTTY_SIZE = 20;
    touchgfx::Unicode::UnicodeChar textDisplayTTYBuffer[TEXTDISPLAYTTY_SIZE];

private:

    /*
     * Callback Declarations
     */
    touchgfx::Callback<loadingScreenViewBase, const touchgfx::AbstractButton&> buttonCallback;

    /*
     * Callback Handler Declarations
     */
    void buttonCallbackHandler(const touchgfx::AbstractButton& src);

};

#endif // LOADINGSCREENVIEWBASE_HPP
