/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/rodeoscreen_screen/rodeoScreenViewBase.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>

rodeoScreenViewBase::rodeoScreenViewBase() :
    buttonCallback(this, &rodeoScreenViewBase::buttonCallbackHandler)
{
    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    nullbutton.setXY(229, 210);
    nullbutton.setBitmaps(touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_NORMAL_ID), touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_PRESSED_ID));
    nullbutton.setAlpha(0);
    nullbutton.setVisible(false);
    nullbutton.setAction(buttonCallback);
    add(nullbutton);
}

rodeoScreenViewBase::~rodeoScreenViewBase()
{

}

void rodeoScreenViewBase::setupScreen()
{

}

void rodeoScreenViewBase::buttonCallbackHandler(const touchgfx::AbstractButton& src)
{
    if (&src == &nullbutton)
    {
        //rodeogotoloadingScreen
        //When nullbutton clicked change screen to loadingScreen
        //Go to loadingScreen with no screen transition
        application().gotoloadingScreenScreenNoTransition();
    }
}
