M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-11-20T20:10:09+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-20T20:10:09+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.890
%
G90
G05
T1
X105.057Y-115.2
X105.057Y-120.2
M30
