/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/menuscreen_screen/menuScreenViewBase.hpp>
#include <touchgfx/Color.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <images/BitmapDatabase.hpp>

menuScreenViewBase::menuScreenViewBase() :
    updateItemCallback(this, &menuScreenViewBase::updateItemCallbackHandler),
    buttonCallback(this, &menuScreenViewBase::buttonCallbackHandler)
{
    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    textRodeo.setXY(202, 128);
    textRodeo.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textRodeo.setLinespacing(0);
    textRodeo.setTypedText(touchgfx::TypedText(T___SINGLEUSE_DL4F));
    textRodeo.setVisible(false);
    add(textRodeo);

    textTest.setXY(202, 128);
    textTest.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textTest.setLinespacing(0);
    textTest.setTypedText(touchgfx::TypedText(T___SINGLEUSE_B4DG));
    textTest.setVisible(false);
    add(textTest);

    textFree.setXY(202, 128);
    textFree.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textFree.setLinespacing(0);
    textFree.setTypedText(touchgfx::TypedText(T___SINGLEUSE_XQPQ));
    textFree.setVisible(false);
    add(textFree);

    nullbutton.setXY(229, 210);
    nullbutton.setBitmaps(touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_NORMAL_ID), touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_PRESSED_ID));
    nullbutton.setAlpha(0);
    nullbutton.setVisible(false);
    nullbutton.setAction(buttonCallback);
    add(nullbutton);

    exitMenuBckgrnd.setPosition(0, 0, 150, 272);
    exitMenuBckgrnd.setColor(touchgfx::Color::getColorFromRGB(230, 41, 41));
    add(exitMenuBckgrnd);

    image1.setXY(-17, 100);
    image1.setBitmap(touchgfx::Bitmap(BITMAP_CLOSELOGO_ID));
    add(image1);

    swipeContainer1.setXY(0, -42);
    swipeContainer1.setPageIndicatorBitmaps(touchgfx::Bitmap(BITMAP_VOIDTEMPLATE_ID), touchgfx::Bitmap(BITMAP_VOIDTEMPLATE_ID));
    swipeContainer1.setPageIndicatorXY(0, 0);
    swipeContainer1.setSwipeCutoff(50);
    swipeContainer1.setEndSwipeElasticWidth(100);

    Simhub.setWidth(480);
    Simhub.setHeight(386);
    imageSH1.setXY(0, 42);
    imageSH1.setBitmap(touchgfx::Bitmap(BITMAP_WAVING_BCKGRND_ID));
    Simhub.add(imageSH1);

    imageSH2.setXY(0, 42);
    imageSH2.setBitmap(touchgfx::Bitmap(BITMAP_BMW_BCKGRND_ID));
    Simhub.add(imageSH2);

    imageSH3.setXY(0, 42);
    imageSH3.setBitmap(touchgfx::Bitmap(BITMAP_FLASH_MCQUEEN_BCKGRND_ID));
    Simhub.add(imageSH3);

    imageSH4.setXY(0, 42);
    imageSH4.setBitmap(touchgfx::Bitmap(BITMAP_GROUPEB_BCKGRND_ID));
    Simhub.add(imageSH4);

    imageSH5.setXY(0, 10);
    imageSH5.setBitmap(touchgfx::Bitmap(BITMAP_KITTENRACE_BCKGRND_ID));
    Simhub.add(imageSH5);

    imageSH6.setXY(0, 42);
    imageSH6.setBitmap(touchgfx::Bitmap(BITMAP_NASCAR_BCKGRND_ID));
    Simhub.add(imageSH6);

    imageSH7.setXY(0, 42);
    imageSH7.setBitmap(touchgfx::Bitmap(BITMAP_RACING_BCKGRND_ID));
    Simhub.add(imageSH7);

    imageSH8.setXY(0, 42);
    imageSH8.setBitmap(touchgfx::Bitmap(BITMAP_XANTIA_BCKGRND_ID));
    Simhub.add(imageSH8);

    logoMenu.setXY(0, 13);
    logoMenu.setBitmap(touchgfx::Bitmap(BITMAP_LOGO_SIMHUB_MENU_ID));
    Simhub.add(logoMenu);

    playMenuButton.setXY(197, 250);
    playMenuButton.setBitmaps(touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUND_ACTION_ID), touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUND_PRESSED_ID));
    playMenuButton.setLabelText(touchgfx::TypedText(T___SINGLEUSE_8SW4));
    playMenuButton.setLabelColor(touchgfx::Color::getColorFromRGB(61, 61, 61));
    playMenuButton.setLabelColorPressed(touchgfx::Color::getColorFromRGB(255, 255, 255));
    playMenuButton.setAction(buttonCallback);
    Simhub.add(playMenuButton);

    swipeContainer1.add(Simhub);

    Gamemode.setWidth(480);
    Gamemode.setHeight(386);
    fromFree.setPosition(0, 42, 50, 50);
    fromFree.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    Gamemode.add(fromFree);

    image2.setXY(0, 42);
    image2.setBitmap(touchgfx::Bitmap(BITMAP_FREEMODE_BCKGRND_ID));
    Gamemode.add(image2);

    imageRodeo.setXY(0, 17);
    imageRodeo.setBitmap(touchgfx::Bitmap(BITMAP_RODEO_BCKGRND_ID));
    Gamemode.add(imageRodeo);

    playButtonMode.setXY(197, 250);
    playButtonMode.setBitmaps(touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUND_ACTION_ID), touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUND_PRESSED_ID));
    playButtonMode.setLabelText(touchgfx::TypedText(T___SINGLEUSE_JD2A));
    playButtonMode.setLabelColor(touchgfx::Color::getColorFromRGB(61, 61, 61));
    playButtonMode.setLabelColorPressed(touchgfx::Color::getColorFromRGB(255, 255, 255));
    playButtonMode.setAction(buttonCallback);
    Gamemode.add(playButtonMode);

    scrollWheel1.setPosition(13, 165, 145, 129);
    scrollWheel1.setHorizontal(false);
    scrollWheel1.setCircular(true);
    scrollWheel1.setEasingEquation(touchgfx::EasingEquations::backEaseOut);
    scrollWheel1.setSwipeAcceleration(10);
    scrollWheel1.setDragAcceleration(10);
    scrollWheel1.setNumberOfItems(5);
    scrollWheel1.setSelectedItemOffset(0);
    scrollWheel1.setOvershootPercentage(75);
    scrollWheel1.setSelectedItemExtraSize(0, 0);
    scrollWheel1.setSelectedItemMargin(0, 0);
    scrollWheel1.setDrawableSize(26, 0);
    scrollWheel1.setDrawables(scrollWheel1ListItems, updateItemCallback,
    
                          scrollWheel1SelectedListItems, updateItemCallback);
    scrollWheel1.animateToItem(0, 0);
    Gamemode.add(scrollWheel1);

    logoMode.setXY(0, 2);
    logoMode.setBitmap(touchgfx::Bitmap(BITMAP_FREEMODE_LOGO_ID));
    Gamemode.add(logoMode);

    swipeContainer1.add(Gamemode);

    Creator.setWidth(480);
    Creator.setHeight(386);
    imageFireBckgrnd.setBitmap(touchgfx::Bitmap(BITMAP_FIREBACKGROUND_ID));
    imageFireBckgrnd.setPosition(0, 42, 480, 272);
    imageFireBckgrnd.setScalingAlgorithm(touchgfx::ScalableImage::NEAREST_NEIGHBOR);
    Creator.add(imageFireBckgrnd);

    bilal.setXY(20, 121);
    bilal.setBitmap(touchgfx::Bitmap(BITMAP_BYOUSFI_ID));
    Creator.add(bilal);

    julien.setXY(320, 121);
    julien.setBitmap(touchgfx::Bitmap(BITMAP_JBURGER_ID));
    Creator.add(julien);

    textArea2.setXY(21, 98);
    textArea2.setColor(touchgfx::Color::getColorFromRGB(252, 0, 0));
    textArea2.setLinespacing(0);
    textArea2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_JIHH));
    Creator.add(textArea2);

    textArea2_1.setXY(308, 98);
    textArea2_1.setColor(touchgfx::Color::getColorFromRGB(252, 0, 0));
    textArea2_1.setLinespacing(0);
    textArea2_1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_K1TM));
    Creator.add(textArea2_1);

    textArea2_1_1.setXY(31, 284);
    textArea2_1_1.setColor(touchgfx::Color::getColorFromRGB(8, 37, 112));
    textArea2_1_1.setLinespacing(0);
    textArea2_1_1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_4N6Y));
    Creator.add(textArea2_1_1);

    textArea2_1_1_1.setXY(330, 287);
    textArea2_1_1_1.setColor(touchgfx::Color::getColorFromRGB(8, 37, 112));
    textArea2_1_1_1.setLinespacing(0);
    textArea2_1_1_1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_Z97T));
    Creator.add(textArea2_1_1_1);

    scalableImage3.setBitmap(touchgfx::Bitmap(BITMAP_CREW_LOGO_ID));
    scalableImage3.setPosition(0, 36, 150, 79);
    scalableImage3.setScalingAlgorithm(touchgfx::ScalableImage::NEAREST_NEIGHBOR);
    Creator.add(scalableImage3);

    swipeContainer1.add(Creator);

    swipeContainer1.setSelectedPage(0);
    add(swipeContainer1);
}

menuScreenViewBase::~menuScreenViewBase()
{

}

void menuScreenViewBase::setupScreen()
{
    scrollWheel1.initialize();
    for (int i = 0; i < scrollWheel1ListItems.getNumberOfDrawables(); i++)
    {
        scrollWheel1ListItems[i].initialize();
    }
    for (int i = 0; i < scrollWheel1SelectedListItems.getNumberOfDrawables(); i++)
    {
        scrollWheel1SelectedListItems[i].initialize();
    }
}

void menuScreenViewBase::buttonCallbackHandler(const touchgfx::AbstractButton& src)
{
    if (&src == &playMenuButton)
    {
        //menuPlayChangeScreenToSimhub
        //When playMenuButton clicked call virtual function
        //Call buttonMenuPlayisTriggered
        buttonMenuPlayisTriggered();
    }
    if (&src == &playButtonMode)
    {
        //menuPlayChangeScreenToMod
        //When playButtonMode clicked call virtual function
        //Call buttonModePlayisTriggered
        buttonModePlayisTriggered();
    }
    if (&src == &nullbutton)
    {
        //menugotoloadingScreen
        //When nullbutton clicked change screen to loadingScreen
        //Go to loadingScreen with no screen transition
        application().gotoloadingScreenScreenNoTransition();
        //loadingotoExitScreen
        //When nullbutton clicked change screen to exitScreen
        //Go to exitScreen with no screen transition
        application().gotoexitScreenScreenNoTransition();
    }
}

void menuScreenViewBase::updateItemCallbackHandler(touchgfx::DrawableListItemsInterface* items, int16_t containerIndex, int16_t itemIndex)
{
    if (items == &scrollWheel1ListItems)
    {
        touchgfx::Drawable* d = items->getDrawable(containerIndex);
        CustomContainer1_1* cc = (CustomContainer1_1*)d;
        scrollWheel1UpdateItem(*cc, itemIndex);
    }
    if (items == &scrollWheel1SelectedListItems)
    {
        touchgfx::Drawable* d = items->getDrawable(containerIndex);
        CustomContainer1* cc = (CustomContainer1*)d;
        scrollWheel1UpdateCenterItem(*cc, itemIndex);
    }
}
