/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/simhubscreen_screen/SimhubScreenViewBase.hpp>
#include <touchgfx/canvas_widget_renderer/CanvasWidgetRenderer.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>
#include <texts/TextKeysAndLanguages.hpp>

SimhubScreenViewBase::SimhubScreenViewBase() :
    buttonCallback(this, &SimhubScreenViewBase::buttonCallbackHandler)
{
    touchgfx::CanvasWidgetRenderer::setupBuffer(canvasBuffer, CANVAS_BUFFER_SIZE);

    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    nullbutton.setXY(229, 210);
    nullbutton.setBitmaps(touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_NORMAL_ID), touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_PRESSED_ID));
    nullbutton.setAlpha(0);
    nullbutton.setVisible(false);
    nullbutton.setAction(buttonCallback);
    add(nullbutton);

    imageExitBckgrnd.setPosition(0, 0, 150, 272);
    imageExitBckgrnd.setColor(touchgfx::Color::getColorFromRGB(230, 41, 41));
    add(imageExitBckgrnd);

    image1.setXY(20, 100);
    image1.setBitmap(touchgfx::Bitmap(BITMAP_CLOSELOGO_ID));
    add(image1);

    swipeContainer1.setXY(0, 0);
    swipeContainer1.setPageIndicatorBitmaps(touchgfx::Bitmap(BITMAP_VOIDTEMPLATE_ID), touchgfx::Bitmap(BITMAP_VOIDTEMPLATE_ID));
    swipeContainer1.setPageIndicatorXY(0, 0);
    swipeContainer1.setSwipeCutoff(150);
    swipeContainer1.setEndSwipeElasticWidth(50);

    swipeContainer1Page1.setWidth(480);
    swipeContainer1Page1.setHeight(272);
    imageSHbckgrnd.setXY(0, 0);
    imageSHbckgrnd.setBitmap(touchgfx::Bitmap(BITMAP_SIMHUBSCREEN_BCKGRN_ID));
    swipeContainer1Page1.add(imageSHbckgrnd);

    lineProgressM1.setXY(21, 68);
    lineProgressM1.setProgressIndicatorPosition(0, 0, 18, 50);
    lineProgressM1.setRange(0, 100);
    lineProgressM1.setBackground(touchgfx::Bitmap(BITMAP_STRAIGHTBAR_ID));
    lineProgressM1Painter.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    lineProgressM1.setPainter(lineProgressM1Painter);
    lineProgressM1.setStart(9, 100);
    lineProgressM1.setEnd(9, 0);
    lineProgressM1.setLineWidth(18);
    lineProgressM1.setLineEndingStyle(touchgfx::Line::BUTT_CAP_ENDING);
    lineProgressM1.setValue(60);
    swipeContainer1Page1.add(lineProgressM1);

    lineProgressM3.setXY(21, 137);
    lineProgressM3.setProgressIndicatorPosition(0, 0, 18, 50);
    lineProgressM3.setRange(0, 100);
    lineProgressM3.setBackground(touchgfx::Bitmap(BITMAP_STRAIGHTBAR_ID));
    lineProgressM3Painter.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    lineProgressM3.setPainter(lineProgressM3Painter);
    lineProgressM3.setStart(9, 100);
    lineProgressM3.setEnd(9, 0);
    lineProgressM3.setLineWidth(18);
    lineProgressM3.setLineEndingStyle(touchgfx::Line::BUTT_CAP_ENDING);
    lineProgressM3.setValue(60);
    swipeContainer1Page1.add(lineProgressM3);

    lineProgressM4.setXY(135, 137);
    lineProgressM4.setProgressIndicatorPosition(0, 0, 18, 50);
    lineProgressM4.setRange(0, 100);
    lineProgressM4.setBackground(touchgfx::Bitmap(BITMAP_STRAIGHTBAR_ID));
    lineProgressM4Painter.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    lineProgressM4.setPainter(lineProgressM4Painter);
    lineProgressM4.setStart(9, 100);
    lineProgressM4.setEnd(9, 0);
    lineProgressM4.setLineWidth(18);
    lineProgressM4.setLineEndingStyle(touchgfx::Line::BUTT_CAP_ENDING);
    lineProgressM4.setValue(60);
    swipeContainer1Page1.add(lineProgressM4);

    lineProgressM2.setXY(135, 64);
    lineProgressM2.setProgressIndicatorPosition(0, 0, 18, 50);
    lineProgressM2.setRange(0, 100);
    lineProgressM2.setBackground(touchgfx::Bitmap(BITMAP_STRAIGHTBAR_ID));
    lineProgressM2Painter.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    lineProgressM2.setPainter(lineProgressM2Painter);
    lineProgressM2.setStart(9, 100);
    lineProgressM2.setEnd(9, 0);
    lineProgressM2.setLineWidth(18);
    lineProgressM2.setLineEndingStyle(touchgfx::Line::BUTT_CAP_ENDING);
    lineProgressM2.setValue(60);
    swipeContainer1Page1.add(lineProgressM2);

    textAngleProgressM3.setXY(21, 157);
    textAngleProgressM3.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textAngleProgressM3.setLinespacing(0);
    Unicode::snprintf(textAngleProgressM3Buffer, TEXTANGLEPROGRESSM3_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_XPGL).getText());
    textAngleProgressM3.setWildcard(textAngleProgressM3Buffer);
    textAngleProgressM3.resizeToCurrentText();
    textAngleProgressM3.setTypedText(touchgfx::TypedText(T___SINGLEUSE_3HZY));
    swipeContainer1Page1.add(textAngleProgressM3);

    textAngleProgressM4.setXY(135, 159);
    textAngleProgressM4.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textAngleProgressM4.setLinespacing(0);
    Unicode::snprintf(textAngleProgressM4Buffer, TEXTANGLEPROGRESSM4_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_WMKC).getText());
    textAngleProgressM4.setWildcard(textAngleProgressM4Buffer);
    textAngleProgressM4.resizeToCurrentText();
    textAngleProgressM4.setTypedText(touchgfx::TypedText(T___SINGLEUSE_VN1Q));
    swipeContainer1Page1.add(textAngleProgressM4);

    textAngleProgressM2.setXY(135, 86);
    textAngleProgressM2.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textAngleProgressM2.setLinespacing(0);
    Unicode::snprintf(textAngleProgressM2Buffer, TEXTANGLEPROGRESSM2_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_0M65).getText());
    textAngleProgressM2.setWildcard(textAngleProgressM2Buffer);
    textAngleProgressM2.resizeToCurrentText();
    textAngleProgressM2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_78RH));
    swipeContainer1Page1.add(textAngleProgressM2);

    textAngleProgressM1.setXY(20, 86);
    textAngleProgressM1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textAngleProgressM1.setLinespacing(0);
    Unicode::snprintf(textAngleProgressM1Buffer, TEXTANGLEPROGRESSM1_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_A7MR).getText());
    textAngleProgressM1.setWildcard(textAngleProgressM1Buffer);
    textAngleProgressM1.resizeToCurrentText();
    textAngleProgressM1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_USNC));
    swipeContainer1Page1.add(textAngleProgressM1);

    imageCar.setXY(-38, 0);
    imageCar.setBitmap(touchgfx::Bitmap(BITMAP_CAR_LOGO_BCKGRND_ID));
    swipeContainer1Page1.add(imageCar);

    boxWithBorderM1.setPosition(212, 5, 120, 50);
    boxWithBorderM1.setColor(touchgfx::Color::getColorFromRGB(127, 127, 127));
    boxWithBorderM1.setBorderColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    boxWithBorderM1.setBorderSize(1);
    swipeContainer1Page1.add(boxWithBorderM1);

    textTitleM1.setXY(257, 6);
    textTitleM1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textTitleM1.setLinespacing(0);
    textTitleM1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_E21Y));
    swipeContainer1Page1.add(textTitleM1);

    textCurrentM1.setXY(222, 36);
    textCurrentM1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textCurrentM1.setLinespacing(0);
    textCurrentM1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_8CQ2));
    swipeContainer1Page1.add(textCurrentM1);

    textCurrentProgressM1.setXY(259, 37);
    textCurrentProgressM1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textCurrentProgressM1.setLinespacing(0);
    Unicode::snprintf(textCurrentProgressM1Buffer, TEXTCURRENTPROGRESSM1_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_D1XG).getText());
    textCurrentProgressM1.setWildcard(textCurrentProgressM1Buffer);
    textCurrentProgressM1.resizeToCurrentText();
    textCurrentProgressM1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_9GYU));
    swipeContainer1Page1.add(textCurrentProgressM1);

    boxWithBorderM2.setPosition(347, 5, 120, 50);
    boxWithBorderM2.setColor(touchgfx::Color::getColorFromRGB(127, 127, 127));
    boxWithBorderM2.setBorderColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    boxWithBorderM2.setBorderSize(1);
    swipeContainer1Page1.add(boxWithBorderM2);

    textTitleM2.setXY(392, 6);
    textTitleM2.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textTitleM2.setLinespacing(0);
    textTitleM2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_5N83));
    swipeContainer1Page1.add(textTitleM2);

    textCurrentM2.setXY(357, 36);
    textCurrentM2.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textCurrentM2.setLinespacing(0);
    textCurrentM2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_VUAF));
    swipeContainer1Page1.add(textCurrentM2);

    textCurrentProgressM2.setXY(394, 37);
    textCurrentProgressM2.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textCurrentProgressM2.setLinespacing(0);
    Unicode::snprintf(textCurrentProgressM2Buffer, TEXTCURRENTPROGRESSM2_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_4P53).getText());
    textCurrentProgressM2.setWildcard(textCurrentProgressM2Buffer);
    textCurrentProgressM2.resizeToCurrentText();
    textCurrentProgressM2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_UP24));
    swipeContainer1Page1.add(textCurrentProgressM2);

    boxWithBorderM3.setPosition(212, 69, 120, 50);
    boxWithBorderM3.setColor(touchgfx::Color::getColorFromRGB(127, 127, 127));
    boxWithBorderM3.setBorderColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    boxWithBorderM3.setBorderSize(1);
    swipeContainer1Page1.add(boxWithBorderM3);

    textTitleM3.setXY(257, 70);
    textTitleM3.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textTitleM3.setLinespacing(0);
    textTitleM3.setTypedText(touchgfx::TypedText(T___SINGLEUSE_OLQG));
    swipeContainer1Page1.add(textTitleM3);

    textCurrentM3.setXY(222, 100);
    textCurrentM3.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textCurrentM3.setLinespacing(0);
    textCurrentM3.setTypedText(touchgfx::TypedText(T___SINGLEUSE_3EEG));
    swipeContainer1Page1.add(textCurrentM3);

    textCurrentProgressM3.setXY(259, 101);
    textCurrentProgressM3.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textCurrentProgressM3.setLinespacing(0);
    Unicode::snprintf(textCurrentProgressM3Buffer, TEXTCURRENTPROGRESSM3_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_G8M7).getText());
    textCurrentProgressM3.setWildcard(textCurrentProgressM3Buffer);
    textCurrentProgressM3.resizeToCurrentText();
    textCurrentProgressM3.setTypedText(touchgfx::TypedText(T___SINGLEUSE_1BSB));
    swipeContainer1Page1.add(textCurrentProgressM3);

    boxWithBorderM4.setPosition(347, 69, 120, 50);
    boxWithBorderM4.setColor(touchgfx::Color::getColorFromRGB(127, 127, 127));
    boxWithBorderM4.setBorderColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    boxWithBorderM4.setBorderSize(1);
    swipeContainer1Page1.add(boxWithBorderM4);

    textTitleM4.setXY(392, 70);
    textTitleM4.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textTitleM4.setLinespacing(0);
    textTitleM4.setTypedText(touchgfx::TypedText(T___SINGLEUSE_647D));
    swipeContainer1Page1.add(textTitleM4);

    textCurrentM4.setXY(357, 100);
    textCurrentM4.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textCurrentM4.setLinespacing(0);
    textCurrentM4.setTypedText(touchgfx::TypedText(T___SINGLEUSE_XUC2));
    swipeContainer1Page1.add(textCurrentM4);

    textCurrentProgressM4.setXY(394, 101);
    textCurrentProgressM4.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textCurrentProgressM4.setLinespacing(0);
    Unicode::snprintf(textCurrentProgressM4Buffer, TEXTCURRENTPROGRESSM4_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_FFHN).getText());
    textCurrentProgressM4.setWildcard(textCurrentProgressM4Buffer);
    textCurrentProgressM4.resizeToCurrentText();
    textCurrentProgressM4.setTypedText(touchgfx::TypedText(T___SINGLEUSE_9RPH));
    swipeContainer1Page1.add(textCurrentProgressM4);

    swipeContainer1.add(swipeContainer1Page1);

    swipeContainer1.setSelectedPage(0);
    add(swipeContainer1);
}

SimhubScreenViewBase::~SimhubScreenViewBase()
{
    touchgfx::CanvasWidgetRenderer::resetBuffer();
}

void SimhubScreenViewBase::setupScreen()
{

}

void SimhubScreenViewBase::buttonCallbackHandler(const touchgfx::AbstractButton& src)
{
    if (&src == &nullbutton)
    {
        //SimhubgotoLoadingScreen
        //When nullbutton clicked change screen to loadingScreen
        //Go to loadingScreen with no screen transition
        application().gotoloadingScreenScreenNoTransition();
    }
}
