/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/freemodescreen_screen/freemodeScreenViewBase.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>

freemodeScreenViewBase::freemodeScreenViewBase() :
    buttonCallback(this, &freemodeScreenViewBase::buttonCallbackHandler)
{
    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    nullbutton.setXY(229, 210);
    nullbutton.setBitmaps(touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_NORMAL_ID), touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_PRESSED_ID));
    nullbutton.setAlpha(0);
    nullbutton.setVisible(false);
    nullbutton.setAction(buttonCallback);
    add(nullbutton);

    box1.setPosition(0, 0, 480, 272);
    box1.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    add(box1);

    textureMapper1.setXY(164, 60);
    textureMapper1.setBitmap(touchgfx::Bitmap(BITMAP_CAR_CHASSIS_ID));
    textureMapper1.setWidth(152);
    textureMapper1.setHeight(152);
    textureMapper1.setBitmapPosition(-34.0f, -34.0f);
    textureMapper1.setScale(1.0f);
    textureMapper1.setCameraDistance(1000.0f);
    textureMapper1.setOrigo(76.0f, 76.0f, 1000.0f);
    textureMapper1.setCamera(76.0f, 76.0f);
    textureMapper1.setAngles(0.0f, 0.0f, 0.0f);
    textureMapper1.setRenderingAlgorithm(touchgfx::TextureMapper::NEAREST_NEIGHBOR);
    add(textureMapper1);
}

freemodeScreenViewBase::~freemodeScreenViewBase()
{

}

void freemodeScreenViewBase::setupScreen()
{

}

void freemodeScreenViewBase::buttonCallbackHandler(const touchgfx::AbstractButton& src)
{
    if (&src == &nullbutton)
    {
        //freemodeotoloadingScreen
        //When nullbutton clicked change screen to loadingScreen
        //Go to loadingScreen with no screen transition
        application().gotoloadingScreenScreenNoTransition();
    }
}
