/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/exitscreen_screen/exitScreenViewBase.hpp>
#include <touchgfx/Color.hpp>
#include <texts/TextKeysAndLanguages.hpp>

exitScreenViewBase::exitScreenViewBase()
{
    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    box1.setPosition(-2, 0, 480, 272);
    box1.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    add(box1);

    test3.setXY(202, 128);
    test3.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    test3.setLinespacing(0);
    test3.setTypedText(touchgfx::TypedText(T___SINGLEUSE_S45C));
    add(test3);

    test2.setXY(202, 128);
    test2.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    test2.setLinespacing(0);
    test2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_4I3X));
    add(test2);

    test1.setXY(202, 128);
    test1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    test1.setLinespacing(0);
    test1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_GJC6));
    add(test1);
}

exitScreenViewBase::~exitScreenViewBase()
{

}

void exitScreenViewBase::setupScreen()
{

}
