/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef FREEMODESCREENVIEWBASE_HPP
#define FREEMODESCREENVIEWBASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <mvp/View.hpp>
#include <gui/freemodescreen_screen/freemodeScreenPresenter.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/Button.hpp>
#include <touchgfx/widgets/TextureMapper.hpp>

class freemodeScreenViewBase : public touchgfx::View<freemodeScreenPresenter>
{
public:
    freemodeScreenViewBase();
    virtual ~freemodeScreenViewBase();
    virtual void setupScreen();

protected:
    FrontendApplication& application() {
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }

    /*
     * Member Declarations
     */
    touchgfx::Box __background;
    touchgfx::Button nullbutton;
    touchgfx::Box box1;
    touchgfx::TextureMapper textureMapper1;

private:

    /*
     * Callback Declarations
     */
    touchgfx::Callback<freemodeScreenViewBase, const touchgfx::AbstractButton&> buttonCallback;

    /*
     * Callback Handler Declarations
     */
    void buttonCallbackHandler(const touchgfx::AbstractButton& src);

};

#endif // FREEMODESCREENVIEWBASE_HPP
