/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef SIMHUBSCREENVIEWBASE_HPP
#define SIMHUBSCREENVIEWBASE_HPP

#include <gui/common/FrontendApplication.hpp>
#include <mvp/View.hpp>
#include <gui/simhubscreen_screen/SimhubScreenPresenter.hpp>
#include <touchgfx/widgets/Box.hpp>
#include <touchgfx/widgets/Button.hpp>
#include <touchgfx/widgets/Image.hpp>
#include <touchgfx/containers/SwipeContainer.hpp>
#include <touchgfx/containers/Container.hpp>
#include <touchgfx/containers/progress_indicators/LineProgress.hpp>
#include <touchgfx/widgets/canvas/PainterRGB565.hpp>
#include <touchgfx/widgets/TextAreaWithWildcard.hpp>
#include <touchgfx/widgets/BoxWithBorder.hpp>
#include <touchgfx/widgets/TextArea.hpp>

class SimhubScreenViewBase : public touchgfx::View<SimhubScreenPresenter>
{
public:
    SimhubScreenViewBase();
    virtual ~SimhubScreenViewBase();
    virtual void setupScreen();

    /*
     * Custom Actions
     */
    virtual void action1()
    {
        // Override and implement this function in Screen1
    }
    

protected:
    FrontendApplication& application() {
        return *static_cast<FrontendApplication*>(touchgfx::Application::getInstance());
    }

    /*
     * Member Declarations
     */
    touchgfx::Box __background;
    touchgfx::Button nullbutton;
    touchgfx::Box imageExitBckgrnd;
    touchgfx::Image image1;
    touchgfx::SwipeContainer swipeContainer1;
    touchgfx::Container swipeContainer1Page1;
    touchgfx::Image imageSHbckgrnd;
    touchgfx::LineProgress lineProgressM1;
    touchgfx::PainterRGB565 lineProgressM1Painter;
    touchgfx::LineProgress lineProgressM3;
    touchgfx::PainterRGB565 lineProgressM3Painter;
    touchgfx::LineProgress lineProgressM4;
    touchgfx::PainterRGB565 lineProgressM4Painter;
    touchgfx::LineProgress lineProgressM2;
    touchgfx::PainterRGB565 lineProgressM2Painter;
    touchgfx::TextAreaWithOneWildcard textAngleProgressM3;
    touchgfx::TextAreaWithOneWildcard textAngleProgressM4;
    touchgfx::TextAreaWithOneWildcard textAngleProgressM2;
    touchgfx::TextAreaWithOneWildcard textAngleProgressM1;
    touchgfx::Image imageCar;
    touchgfx::BoxWithBorder boxWithBorderM1;
    touchgfx::TextArea textTitleM1;
    touchgfx::TextArea textCurrentM1;
    touchgfx::TextAreaWithOneWildcard textCurrentProgressM1;
    touchgfx::BoxWithBorder boxWithBorderM2;
    touchgfx::TextArea textTitleM2;
    touchgfx::TextArea textCurrentM2;
    touchgfx::TextAreaWithOneWildcard textCurrentProgressM2;
    touchgfx::BoxWithBorder boxWithBorderM3;
    touchgfx::TextArea textTitleM3;
    touchgfx::TextArea textCurrentM3;
    touchgfx::TextAreaWithOneWildcard textCurrentProgressM3;
    touchgfx::BoxWithBorder boxWithBorderM4;
    touchgfx::TextArea textTitleM4;
    touchgfx::TextArea textCurrentM4;
    touchgfx::TextAreaWithOneWildcard textCurrentProgressM4;

    /*
     * Wildcard Buffers
     */
    static const uint16_t TEXTANGLEPROGRESSM3_SIZE = 4;
    touchgfx::Unicode::UnicodeChar textAngleProgressM3Buffer[TEXTANGLEPROGRESSM3_SIZE];
    static const uint16_t TEXTANGLEPROGRESSM4_SIZE = 4;
    touchgfx::Unicode::UnicodeChar textAngleProgressM4Buffer[TEXTANGLEPROGRESSM4_SIZE];
    static const uint16_t TEXTANGLEPROGRESSM2_SIZE = 4;
    touchgfx::Unicode::UnicodeChar textAngleProgressM2Buffer[TEXTANGLEPROGRESSM2_SIZE];
    static const uint16_t TEXTANGLEPROGRESSM1_SIZE = 4;
    touchgfx::Unicode::UnicodeChar textAngleProgressM1Buffer[TEXTANGLEPROGRESSM1_SIZE];
    static const uint16_t TEXTCURRENTPROGRESSM1_SIZE = 4;
    touchgfx::Unicode::UnicodeChar textCurrentProgressM1Buffer[TEXTCURRENTPROGRESSM1_SIZE];
    static const uint16_t TEXTCURRENTPROGRESSM2_SIZE = 4;
    touchgfx::Unicode::UnicodeChar textCurrentProgressM2Buffer[TEXTCURRENTPROGRESSM2_SIZE];
    static const uint16_t TEXTCURRENTPROGRESSM3_SIZE = 4;
    touchgfx::Unicode::UnicodeChar textCurrentProgressM3Buffer[TEXTCURRENTPROGRESSM3_SIZE];
    static const uint16_t TEXTCURRENTPROGRESSM4_SIZE = 4;
    touchgfx::Unicode::UnicodeChar textCurrentProgressM4Buffer[TEXTCURRENTPROGRESSM4_SIZE];

private:

    /*
     * Canvas Buffer Size
     */
    static const uint32_t CANVAS_BUFFER_SIZE = 7200;
    uint8_t canvasBuffer[CANVAS_BUFFER_SIZE];

    /*
     * Callback Declarations
     */
    touchgfx::Callback<SimhubScreenViewBase, const touchgfx::AbstractButton&> buttonCallback;

    /*
     * Callback Handler Declarations
     */
    void buttonCallbackHandler(const touchgfx::AbstractButton& src);

};

#endif // SIMHUBSCREENVIEWBASE_HPP
