/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef FRONTENDAPPLICATIONBASE_HPP
#define FRONTENDAPPLICATIONBASE_HPP

#include <mvp/MVPApplication.hpp>
#include <gui/model/Model.hpp>

class FrontendHeap;

class FrontendApplicationBase : public touchgfx::MVPApplication
{
public:
    FrontendApplicationBase(Model& m, FrontendHeap& heap);
    virtual ~FrontendApplicationBase() { }

    virtual void changeToStartScreen()
    {
        gotomenuScreenScreenNoTransition();
    }

    // SimhubScreen
    void gotoSimhubScreenScreenNoTransition();

    // loadingScreen
    void gotoloadingScreenScreenNoTransition();

    // menuScreen
    void gotomenuScreenScreenNoTransition();

    // exitScreen
    void gotoexitScreenScreenNoTransition();

    // freemodeScreen
    void gotofreemodeScreenScreenNoTransition();

    // rodeoScreen
    void gotorodeoScreenScreenNoTransition();

protected:
    touchgfx::Callback<FrontendApplicationBase> transitionCallback;
    FrontendHeap& frontendHeap;
    Model& model;

    // SimhubScreen
    void gotoSimhubScreenScreenNoTransitionImpl();

    // loadingScreen
    void gotoloadingScreenScreenNoTransitionImpl();

    // menuScreen
    void gotomenuScreenScreenNoTransitionImpl();

    // exitScreen
    void gotoexitScreenScreenNoTransitionImpl();

    // freemodeScreen
    void gotofreemodeScreenScreenNoTransitionImpl();

    // rodeoScreen
    void gotorodeoScreenScreenNoTransitionImpl();
};

#endif // FRONTENDAPPLICATIONBASE_HPP
