/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#ifndef FRONTENDHEAPBASE_HPP
#define FRONTENDHEAPBASE_HPP

#include <common/Meta.hpp>
#include <common/Partition.hpp>
#include <mvp/MVPHeap.hpp>

#include <touchgfx/transitions/NoTransition.hpp>
#include <gui/common/FrontendApplication.hpp>
#include <gui/model/Model.hpp>

#include <gui/simhubscreen_screen/SimhubScreenView.hpp>
#include <gui/simhubscreen_screen/SimhubScreenPresenter.hpp>
#include <gui/loadingscreen_screen/loadingScreenView.hpp>
#include <gui/loadingscreen_screen/loadingScreenPresenter.hpp>
#include <gui/menuscreen_screen/menuScreenView.hpp>
#include <gui/menuscreen_screen/menuScreenPresenter.hpp>
#include <gui/exitscreen_screen/exitScreenView.hpp>
#include <gui/exitscreen_screen/exitScreenPresenter.hpp>
#include <gui/freemodescreen_screen/freemodeScreenView.hpp>
#include <gui/freemodescreen_screen/freemodeScreenPresenter.hpp>
#include <gui/rodeoscreen_screen/rodeoScreenView.hpp>
#include <gui/rodeoscreen_screen/rodeoScreenPresenter.hpp>


/**
 * This class provides the memory that shall be used for memory allocations
 * in the frontend. A single instance of the FrontendHeap is allocated once (in heap
 * memory), and all other frontend objects such as views, presenters and data model are
 * allocated within the scope of this FrontendHeap. As such, the RAM usage of the entire
 * user interface is sizeof(FrontendHeap).
 *
 * @note The FrontendHeap reserves memory for the most memory-consuming presenter and
 * view only. The largest of these classes are determined at compile-time using template
 * magic. As such, it is important to add all presenters, views and transitions to the
 * type lists in this class.
 *
 */
class FrontendHeapBase : public touchgfx::MVPHeap
{
public:
    /**
     * A list of all view types. Must end with meta::Nil.
     * @note All view types used in the application MUST be added to this list!
     */
    typedef touchgfx::meta::TypeList< SimhubScreenView,
            touchgfx::meta::TypeList< loadingScreenView,
            touchgfx::meta::TypeList< menuScreenView,
            touchgfx::meta::TypeList< exitScreenView,
            touchgfx::meta::TypeList< freemodeScreenView,
            touchgfx::meta::TypeList< rodeoScreenView,
            touchgfx::meta::Nil > > > > >
            > GeneratedViewTypes;

    /**
     * Determine (compile time) the View type of largest size.
     */
    typedef touchgfx::meta::select_type_maxsize< GeneratedViewTypes >::type MaxGeneratedViewType;

    /**
     * A list of all presenter types. Must end with meta::Nil.
     * @note All presenter types used in the application MUST be added to this list!
     */
    typedef touchgfx::meta::TypeList< SimhubScreenPresenter,
            touchgfx::meta::TypeList< loadingScreenPresenter,
            touchgfx::meta::TypeList< menuScreenPresenter,
            touchgfx::meta::TypeList< exitScreenPresenter,
            touchgfx::meta::TypeList< freemodeScreenPresenter,
            touchgfx::meta::TypeList< rodeoScreenPresenter,
            touchgfx::meta::Nil > > > > >
            > GeneratedPresenterTypes;

    /**
     * Determine (compile time) the Presenter type of largest size.
     */
    typedef touchgfx::meta::select_type_maxsize< GeneratedPresenterTypes >::type MaxGeneratedPresenterType;

    /**
     * A list of all transition types. Must end with meta::Nil.
     * @note All transition types used in the application MUST be added to this list!
     */
    typedef touchgfx::meta::TypeList< touchgfx::NoTransition,
            touchgfx::meta::Nil
            > GeneratedTransitionTypes;

    /**
     * Determine (compile time) the Transition type of largest size.
     */
    typedef touchgfx::meta::select_type_maxsize< GeneratedTransitionTypes >::type MaxGeneratedTransitionType;

    virtual void gotoStartScreen(FrontendApplication& app)
    {
        app.gotomenuScreenScreenNoTransition();
    }
protected:
    FrontendHeapBase(touchgfx::AbstractPartition& presenters, touchgfx::AbstractPartition& views, touchgfx::AbstractPartition& transitions, FrontendApplication& app)
        : MVPHeap(presenters, views, transitions, app)
    {

    }

};

#endif // FRONTENDHEAPBASE_HPP
