/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <new>
#include <gui_generated/common/FrontendApplicationBase.hpp>
#include <gui/common/FrontendHeap.hpp>
#include <touchgfx/transitions/NoTransition.hpp>
#include <texts/TextKeysAndLanguages.hpp>
#include <touchgfx/Texts.hpp>
#include <touchgfx/hal/HAL.hpp>
#include <platform/driver/lcd/LCD16bpp.hpp>
#include <gui/simhubscreen_screen/SimhubScreenView.hpp>
#include <gui/simhubscreen_screen/SimhubScreenPresenter.hpp>
#include <gui/loadingscreen_screen/loadingScreenView.hpp>
#include <gui/loadingscreen_screen/loadingScreenPresenter.hpp>
#include <gui/menuscreen_screen/menuScreenView.hpp>
#include <gui/menuscreen_screen/menuScreenPresenter.hpp>
#include <gui/exitscreen_screen/exitScreenView.hpp>
#include <gui/exitscreen_screen/exitScreenPresenter.hpp>
#include <gui/freemodescreen_screen/freemodeScreenView.hpp>
#include <gui/freemodescreen_screen/freemodeScreenPresenter.hpp>
#include <gui/rodeoscreen_screen/rodeoScreenView.hpp>
#include <gui/rodeoscreen_screen/rodeoScreenPresenter.hpp>

using namespace touchgfx;

FrontendApplicationBase::FrontendApplicationBase(Model& m, FrontendHeap& heap)
    : touchgfx::MVPApplication(),
      transitionCallback(),
      frontendHeap(heap),
      model(m)
{
    touchgfx::HAL::getInstance()->setDisplayOrientation(touchgfx::ORIENTATION_LANDSCAPE);
    touchgfx::Texts::setLanguage(GB);
    reinterpret_cast<touchgfx::LCD16bpp&>(touchgfx::HAL::lcd()).enableTextureMapperAll();
    reinterpret_cast<touchgfx::LCD16bpp&>(touchgfx::HAL::lcd()).enableDecompressorL8_All();
    reinterpret_cast<touchgfx::LCD16bpp&>(touchgfx::HAL::lcd()).enableDecompressorRGB();
}

/*
 * Screen Transition Declarations
 */

// SimhubScreen

void FrontendApplicationBase::gotoSimhubScreenScreenNoTransition()
{
    transitionCallback = touchgfx::Callback<FrontendApplicationBase>(this, &FrontendApplicationBase::gotoSimhubScreenScreenNoTransitionImpl);
    pendingScreenTransitionCallback = &transitionCallback;
}

void FrontendApplicationBase::gotoSimhubScreenScreenNoTransitionImpl()
{
    touchgfx::makeTransition<SimhubScreenView, SimhubScreenPresenter, touchgfx::NoTransition, Model >(&currentScreen, &currentPresenter, frontendHeap, &currentTransition, &model);
}

// loadingScreen

void FrontendApplicationBase::gotoloadingScreenScreenNoTransition()
{
    transitionCallback = touchgfx::Callback<FrontendApplicationBase>(this, &FrontendApplicationBase::gotoloadingScreenScreenNoTransitionImpl);
    pendingScreenTransitionCallback = &transitionCallback;
}

void FrontendApplicationBase::gotoloadingScreenScreenNoTransitionImpl()
{
    touchgfx::makeTransition<loadingScreenView, loadingScreenPresenter, touchgfx::NoTransition, Model >(&currentScreen, &currentPresenter, frontendHeap, &currentTransition, &model);
}

// menuScreen

void FrontendApplicationBase::gotomenuScreenScreenNoTransition()
{
    transitionCallback = touchgfx::Callback<FrontendApplicationBase>(this, &FrontendApplicationBase::gotomenuScreenScreenNoTransitionImpl);
    pendingScreenTransitionCallback = &transitionCallback;
}

void FrontendApplicationBase::gotomenuScreenScreenNoTransitionImpl()
{
    touchgfx::makeTransition<menuScreenView, menuScreenPresenter, touchgfx::NoTransition, Model >(&currentScreen, &currentPresenter, frontendHeap, &currentTransition, &model);
}

// exitScreen

void FrontendApplicationBase::gotoexitScreenScreenNoTransition()
{
    transitionCallback = touchgfx::Callback<FrontendApplicationBase>(this, &FrontendApplicationBase::gotoexitScreenScreenNoTransitionImpl);
    pendingScreenTransitionCallback = &transitionCallback;
}

void FrontendApplicationBase::gotoexitScreenScreenNoTransitionImpl()
{
    touchgfx::makeTransition<exitScreenView, exitScreenPresenter, touchgfx::NoTransition, Model >(&currentScreen, &currentPresenter, frontendHeap, &currentTransition, &model);
}

// freemodeScreen

void FrontendApplicationBase::gotofreemodeScreenScreenNoTransition()
{
    transitionCallback = touchgfx::Callback<FrontendApplicationBase>(this, &FrontendApplicationBase::gotofreemodeScreenScreenNoTransitionImpl);
    pendingScreenTransitionCallback = &transitionCallback;
}

void FrontendApplicationBase::gotofreemodeScreenScreenNoTransitionImpl()
{
    touchgfx::makeTransition<freemodeScreenView, freemodeScreenPresenter, touchgfx::NoTransition, Model >(&currentScreen, &currentPresenter, frontendHeap, &currentTransition, &model);
}

// rodeoScreen

void FrontendApplicationBase::gotorodeoScreenScreenNoTransition()
{
    transitionCallback = touchgfx::Callback<FrontendApplicationBase>(this, &FrontendApplicationBase::gotorodeoScreenScreenNoTransitionImpl);
    pendingScreenTransitionCallback = &transitionCallback;
}

void FrontendApplicationBase::gotorodeoScreenScreenNoTransitionImpl()
{
    touchgfx::makeTransition<rodeoScreenView, rodeoScreenPresenter, touchgfx::NoTransition, Model >(&currentScreen, &currentPresenter, frontendHeap, &currentTransition, &model);
}
