/*********************************************************************************/
/********** THIS FILE IS GENERATED BY TOUCHGFX DESIGNER, DO NOT MODIFY ***********/
/*********************************************************************************/
#include <gui_generated/loadingscreen_screen/loadingScreenViewBase.hpp>
#include <touchgfx/Color.hpp>
#include <images/BitmapDatabase.hpp>
#include <texts/TextKeysAndLanguages.hpp>

loadingScreenViewBase::loadingScreenViewBase() :
    buttonCallback(this, &loadingScreenViewBase::buttonCallbackHandler)
{
    __background.setPosition(0, 0, 480, 272);
    __background.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    add(__background);

    nullbutton.setXY(229, 210);
    nullbutton.setBitmaps(touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_NORMAL_ID), touchgfx::Bitmap(BITMAP_ALTERNATE_THEME_IMAGES_WIDGETS_BUTTON_REGULAR_HEIGHT_50_MEDIUM_ROUNDED_PRESSED_ID));
    nullbutton.setAlpha(0);
    nullbutton.setVisible(false);
    nullbutton.setAction(buttonCallback);
    add(nullbutton);

    formBackground.setPosition(0, 0, 480, 272);
    formBackground.setColor(touchgfx::Color::getColorFromRGB(255, 255, 255));
    add(formBackground);

    imagemapCorncat.setXY(311, 21);
    imagemapCorncat.setBitmap(touchgfx::Bitmap(BITMAP_CORN_CAT_ID));
    imagemapCorncat.setWidth(152);
    imagemapCorncat.setHeight(231);
    imagemapCorncat.setBitmapPosition(-12.5f, 5.5f);
    imagemapCorncat.setScale(1.0f);
    imagemapCorncat.setCameraDistance(1000.0f);
    imagemapCorncat.setOrigo(76.0f, 115.5f, 1000.0f);
    imagemapCorncat.setCamera(76.0f, 115.5f);
    imagemapCorncat.setAngles(0.0f, 0.0f, 0.0f);
    imagemapCorncat.setRenderingAlgorithm(touchgfx::TextureMapper::NEAREST_NEIGHBOR);
    add(imagemapCorncat);

    textL3.setXY(191, 9);
    textL3.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textL3.setLinespacing(0);
    textL3.setTypedText(touchgfx::TypedText(T___SINGLEUSE_4OKL));
    add(textL3);

    textL2.setXY(191, 9);
    textL2.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textL2.setLinespacing(0);
    textL2.setTypedText(touchgfx::TypedText(T___SINGLEUSE_R11L));
    add(textL2);

    textL1.setXY(191, 9);
    textL1.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textL1.setLinespacing(0);
    textL1.setTypedText(touchgfx::TypedText(T___SINGLEUSE_WNAF));
    add(textL1);

    textDisplayTTY.setXY(180, 86);
    textDisplayTTY.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textDisplayTTY.setLinespacing(0);
    Unicode::snprintf(textDisplayTTYBuffer, TEXTDISPLAYTTY_SIZE, "%s", touchgfx::TypedText(T___SINGLEUSE_75JC).getText());
    textDisplayTTY.setWildcard(textDisplayTTYBuffer);
    textDisplayTTY.resizeToCurrentText();
    textDisplayTTY.setTypedText(touchgfx::TypedText(T___SINGLEUSE_WKJM));
    add(textDisplayTTY);

    InitButton.setXY(20, 78);
    InitButton.setBitmaps(touchgfx::Bitmap(BITMAP_SIMHUB_LOGO_ID), touchgfx::Bitmap(BITMAP_SIMHUB_LOGO_N_ID));
    InitButton.setVisible(false);
    InitButton.setAction(buttonCallback);
    add(InitButton);

    textInitSystem.setXY(45, 173);
    textInitSystem.setColor(touchgfx::Color::getColorFromRGB(0, 0, 0));
    textInitSystem.setLinespacing(0);
    textInitSystem.setTypedText(touchgfx::TypedText(T___SINGLEUSE_WBO9));
    textInitSystem.setVisible(false);
    add(textInitSystem);
}

loadingScreenViewBase::~loadingScreenViewBase()
{

}

void loadingScreenViewBase::setupScreen()
{

}

void loadingScreenViewBase::buttonCallbackHandler(const touchgfx::AbstractButton& src)
{
    if (&src == &InitButton)
    {
        //LoadinInitChangeScreenToMenu
        //When InitButton clicked call virtual function
        //Call buttonlaunchInitSystem
        buttonlaunchInitSystem();
    }
    if (&src == &nullbutton)
    {
        //loadingotofreemodeScreen
        //When nullbutton clicked change screen to freemodeScreen
        //Go to freemodeScreen with no screen transition
        application().gotofreemodeScreenScreenNoTransition();
        //loadingotosimhubScreen
        //When nullbutton clicked change screen to SimhubScreen
        //Go to SimhubScreen with no screen transition
        application().gotoSimhubScreenScreenNoTransition();
        //loadingotomenuScreen
        //When nullbutton clicked change screen to menuScreen
        //Go to menuScreen with no screen transition
        application().gotomenuScreenScreenNoTransition();
        //loadingotoexitScreen
        //When nullbutton clicked change screen to exitScreen
        //Go to exitScreen with no screen transition
        application().gotoexitScreenScreenNoTransition();
        //loadingotorodeoScreen
        //When nullbutton clicked change screen to rodeoScreen
        //Go to rodeoScreen with no screen transition
        application().gotorodeoScreenScreenNoTransition();
    }
}
